### PR TITLE
Decode tab-name

### PR DESCRIPTION
**Pull request by zaucker**
Umlaute in .cfg  file tab-name entries must be decoded.

### CODE REVIEW

**Comment by oetiker** [comment]
I think we had this issue before ... the decoding has to happen when the cfg file is read ... it is not particular to tab names.

**Comment by zaucker** [comment]
> I think we had this issue before ... the decoding has to happen when the cfg file is read ... it is not particular to tab names.

Ah, ok. I changed it, unfortunately, it will only have the desired effect with a fix in Config::Grammar (I previously only patched it for the static case, but not the dynamic config loader). But it won't break anything either.

**Comment by oetiker** [comment]
ok will merge please send the patch for Config::Grammar to david.

**Comment by zaucker** [comment]
> ok will merge please send the patch for Config::Grammar to david.

Thanks, https://github.com/schweikert/Config-Grammar/pull/5 created.

**Pull request merged**
